_wandb:
    value:
        cli_version: 0.21.2
        e:
            fw7wrhrkcf6rdmsb39xc2d7cxys3kny5:
                args:
                    - --config
                    - tinystories
                    - --lr
                    - "5e-3"
                    - --batch_size
                    - "256"
                    - --max_steps
                    - "5000"
                    - --warmup_steps
                    - "200"
                    - --log_interval
                    - "50"
                    - --eval_interval
                    - "250"
                    - --checkpoint_interval
                    - "1000"
                    - --checkpoint_dir
                    - checkpoints/lr_5e-3
                    - --train_data
                    - data/tinystories_train_encoded.npy
                    - --val_data
                    - data/tinystories_valid_encoded.npy
                    - --wandb
                    - --run_name
                    - lr_5e-3
                codePath: scripts/train_lm.py
                codePathLocal: scripts/train_lm.py
                cpu_count: 104
                cpu_count_logical: 104
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "315396816896"
                        used: "117898264576"
                email: xli8@andrew.cmu.edu
                executable: /ocean/projects/cis250265p/xli45/assignment1-basics/.venv/bin/python
                git:
                    commit: 1e3c3ffeec9d0852c7a42d59a7f178c1ccd51ba0
                    remote: https://github.com/XLOverflow/assignment1-basics.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-8a42f256-eb3e-f787-ea8d-8b1a28fe5437
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-ed909c33-d131-3a36-0570-60607be1e873
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-c3d5c3f1-f271-8686-399c-0b8b38d935f9
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-b37bfa70-2656-e665-64ed-573d4f2f7fed
                host: w005.ib.bridges2.psc.edu
                memory:
                    total: "2164156493824"
                os: Linux-4.18.0-553.36.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /ocean/projects/cis250265p/xli45/assignment1-basics/scripts/train_lm.py
                python: CPython 3.12.7
                root: /ocean/projects/cis250265p/xli45/assignment1-basics
                slurm:
                    cluster_name: bridges2
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "48"
                    export_env: ALL
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: cis260009p
                    job_cpus_per_node: "48"
                    job_cpus_per_node_pack_group_0: "48"
                    job_gid: "26783"
                    job_gpus: 0,1,2,3
                    job_id: "37422165"
                    job_name: Interact
                    job_nodelist: w005
                    job_num_nodes: "1"
                    job_partition: GPU-shared
                    job_qos: gpuinteract
                    job_uid: "99304"
                    job_user: xli45
                    jobid: "37422165"
                    launch_node_ipaddr: 10.8.11.29
                    localid: "0"
                    mpi_type: none
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: w005
                    prio_process: "0"
                    procid: "0"
                    pty_port: "41271"
                    pty_win_col: "265"
                    pty_win_row: "28"
                    script_context: prolog_task
                    srun_comm_host: 10.8.11.29
                    srun_comm_port: "40225"
                    step_id: "4294967290"
                    step_launcher_port: "40225"
                    step_nodelist: w005
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /ocean/projects/cis250265p/xli45/assignment1-basics
                    submit_host: br011.ib.bridges2.psc.edu
                    task_pid: "88243"
                    tasks_per_node: "48"
                    topology_addr: w005
                    topology_addr_pattern: node
                    working_cluster: bridges2:br003:6810:9728:109
                startedAt: "2026-02-08T18:30:45.563092Z"
                writerId: fw7wrhrkcf6rdmsb39xc2d7cxys3kny5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.7
            "5": 0.21.2
            "8":
                - 2
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 256
beta1:
    value: 0.9
beta2:
    value: 0.999
checkpoint_dir:
    value: checkpoints/lr_5e-3
checkpoint_interval:
    value: 1000
config:
    value: tinystories
context_length:
    value: null
d_ff:
    value: null
d_model:
    value: null
device:
    value: cuda
eps:
    value: 1e-08
eval_batches:
    value: 20
eval_interval:
    value: 250
ffn_type:
    value: swiglu
log_interval:
    value: 50
lr:
    value: 0.005
max_grad_norm:
    value: 1
max_steps:
    value: 5000
min_lr:
    value: 0.0001
num_heads:
    value: null
num_layers:
    value: null
remove_rmsnorm:
    value: false
remove_rope:
    value: false
resume:
    value: null
rope_theta:
    value: null
run_name:
    value: lr_5e-3
train_data:
    value: data/tinystories_train_encoded.npy
use_post_norm:
    value: false
val_data:
    value: data/tinystories_valid_encoded.npy
vocab_size:
    value: null
wandb:
    value: true
warmup_steps:
    value: 200
weight_decay:
    value: 0.1
